{
  "functionName": "extractConnections",
  "logStart": "🔍 Iniciando extração de conexões no LinkedIn...",
  "connectionsArray": "let linkedinConnections = [];",
  "cardSelector": "document.querySelectorAll(\".mn-connection-card\").forEach(card => {",
  "nameElementSelector": "const nameElement = card.querySelector(\".mn-connection-card__name\");",
  "linkElementSelector": "const linkElement = card.querySelector(\"a[href*='/in/']\");",
  "jobElementSelector": "const jobElement = card.querySelector(\".mn-connection-card__occupation\");",
  "nameExtraction": "const name = nameElement ? nameElement.innerText.trim() : \"Sem nome\";",
  "profileUrlExtraction": "const profileurl = linkElement ? `https://www.linkedin.com${linkElement.getAttribute(\"href\").split(\"?\")[0]}` : \"Sem URL\";",
  "jobTitleExtraction": "const jobtitle = jobElement ? jobElement.innerText.trim() : \"N/A\";",
  "duplicateCheck": "if (!linkedinConnections.some(conn => conn.profileurl === profileurl)) {",
  "connectionPush": "linkedinConnections.push({ name, jobtitle, profileurl });",
  "connectionPushEnd": "}",
  "cardSelectorEnd": "});",
  "dataCheck": "if (linkedinConnections.length > 0) {",
  "logExtractedConnections": "console.log(\"📌 Conexões extraídas:\", linkedinConnections);",
  "sendMessageToPopup": "chrome.runtime.sendMessage({ action: \"scrapedData\", data: linkedinConnections })",
  "sendMessageSuccessLog": ".then(() => console.log(\"📤 Dados enviados ao popup com sucesso!\"))",
  "sendMessageErrorLog": ".catch(err => console.error(\"❌ Erro ao enviar os dados:\", err));",
  "dataCheckEnd": "} else {",
  "noConnectionsFoundLog": "console.log(\"⚠️ Nenhuma conexão encontrada.\");",
  "functionEnd": "}"
}
